function J_ll = J_ll_computable(in1,in2,in3)
%J_ll_computable
%    J_ll = J_ll_computable(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Jul-2024 22:49:17

Ll1 = in2(1,:);
Ll2 = in2(2,:);
Ll3 = in2(3,:);
Ll4 = in2(4,:);
ql1 = in1(1,:);
ql2 = in1(2,:);
ql3 = in1(3,:);
ql4 = in1(4,:);
xg1 = in3(1,:);
xg2 = in3(2,:);
xg3 = in3(3,:);
xg4 = in3(4,:);
xg5 = in3(5,:);
xg6 = in3(6,:);
xg7 = in3(7,:);
xg8 = in3(8,:);
xg9 = in3(9,:);
t2 = cos(ql2);
t3 = cos(ql3);
t4 = sin(ql2);
t5 = sin(ql3);
t7 = pi./2.0;
t6 = Ll2.*t4;
t8 = Ll3.*t3.*t4;
t9 = -t7;
t10 = ql1+t7;
t21 = t2.*6.123233995736766e-17;
t11 = ql4+t9;
t12 = cos(t10);
t13 = sin(t10);
t32 = t21-6.123233995736766e-17;
t14 = cos(t11);
t15 = sin(t11);
t16 = t2.*t12;
t17 = t2.*t13;
t22 = t4.*t12.*6.123233995736766e-17;
t23 = t4.*t13.*6.123233995736766e-17;
t25 = t6.*t12.*6.123233995736766e-17;
t26 = t6.*t13.*6.123233995736766e-17;
t35 = Ll3.*t5.*t32;
t18 = Ll2.*t16;
t19 = Ll2.*t17;
t24 = -t23;
t27 = t17+t22;
t33 = t16.*3.749399456654644e-33;
t34 = t17.*3.749399456654644e-33;
t20 = -t18;
t28 = t16+t24;
t29 = Ll3.*t3.*t27;
t36 = t13+t22+t34;
t37 = t12+t24+t33;
t30 = Ll3.*t3.*t28;
t38 = Ll3.*t5.*t36;
t39 = Ll3.*t5.*t37;
t31 = -t30;
J_ll = (t19+t25+t29+t39+xg6).^2+(t20+t26+t31+t38+xg4).^2+(t19+t25+xg3).^2+(t20+t26+xg1).^2+(t19+t25+t29+t39+xg9+Ll4.*t14.*(t3.*t27+t5.*t37)-Ll4.*t15.*(t5.*t27-t3.*t37)).^2+(t20+t26+t31+t38+xg7-Ll4.*t14.*(t3.*t28-t5.*t36)+Ll4.*t15.*(t5.*t28+t3.*t36)).^2+(Ll1+t6+t8+t35-xg5).^2+(Ll1+t6-xg2).^2+(Ll1+t6+t8+t35-xg8+Ll4.*t14.*(t3.*t4+t5.*t32)-Ll4.*t15.*(t4.*t5-t3.*t32)).^2;
end
