function J_rl = J_rl_computable(in1,in2,in3)
%J_rl_computable
%    J_rl = J_rl_computable(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Jul-2024 22:49:11

Ll1 = in2(1,:);
Ll2 = in2(2,:);
Ll3 = in2(3,:);
Ll4 = in2(4,:);
ql1 = in1(1,:);
ql2 = in1(2,:);
ql3 = in1(3,:);
ql4 = in1(4,:);
xg1 = in3(1,:);
xg2 = in3(2,:);
xg3 = in3(3,:);
xg4 = in3(4,:);
xg5 = in3(5,:);
xg6 = in3(6,:);
xg7 = in3(7,:);
xg8 = in3(8,:);
xg9 = in3(9,:);
t2 = cos(ql2);
t3 = cos(ql3);
t4 = sin(ql2);
t5 = sin(ql3);
t7 = -Ll1;
t8 = pi./2.0;
t6 = Ll2.*t4;
t9 = Ll3.*t3.*t4;
t10 = -t8;
t11 = ql4+t8;
t22 = t2.*6.123233995736766e-17;
t12 = ql1+t10;
t13 = cos(t11);
t14 = sin(t11);
t33 = t22-6.123233995736766e-17;
t15 = cos(t12);
t16 = sin(t12);
t34 = Ll3.*t5.*t33;
t17 = t2.*t15;
t18 = t2.*t16;
t23 = t4.*t15.*6.123233995736766e-17;
t24 = t4.*t16.*6.123233995736766e-17;
t26 = t6.*t15.*6.123233995736766e-17;
t27 = t6.*t16.*6.123233995736766e-17;
t19 = Ll2.*t17;
t20 = Ll2.*t18;
t25 = -t24;
t28 = t18+t23;
t35 = t17.*3.749399456654644e-33;
t36 = t18.*3.749399456654644e-33;
t21 = -t19;
t29 = t17+t25;
t30 = Ll3.*t3.*t28;
t37 = t16+t23+t36;
t38 = t15+t25+t35;
t31 = Ll3.*t3.*t29;
t39 = Ll3.*t5.*t37;
t40 = Ll3.*t5.*t38;
t32 = -t31;
J_rl = (t21+t27+t32+t39+xg4).^2+(t21+t27+xg1).^2+(t21+t27+t32+t39+xg7-Ll4.*t13.*(t3.*t29-t5.*t37)+Ll4.*t14.*(t5.*t29+t3.*t37)).^2+(Ll1-t6+xg2).^2+(t6+t7+t9+t34-xg5).^2+(t20+t26+t30+t40-xg6).^2+(t20+t26-xg3).^2+(t6+t7+t9+t34-xg8+Ll4.*t13.*(t3.*t4+t5.*t33)-Ll4.*t14.*(t4.*t5-t3.*t33)).^2+(t20+t26+t30+t40-xg9+Ll4.*t13.*(t3.*t28+t5.*t38)-Ll4.*t14.*(t5.*t28-t3.*t38)).^2;
end
